#Writing initials
#10-17-2019
#CTI-110 P4T1B
#Jeremy Julch




import turtle
turtle.pensize('2')
turtle.pencolor('purple')
turtle.fillcolor('purple')
turtle.bgcolor('pink')
turtle.pendown()
turtle.begin_fill()
turtle.left(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(90)
turtle.left(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(140)
turtle.right(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(120)
turtle.right(90)
turtle.forward(110)
turtle.end_fill()
turtle.penup()
turtle.right(180)
turtle.forward(140)
turtle.pendown()
turtle.begin_fill()
turtle.left(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(90)
turtle.left(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(140)
turtle.right(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(120)
turtle.right(90)
turtle.forward(110)
turtle.end_fill()
